# Generated by Django 5.2 on 2025-05-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dp_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dp_name', models.CharField(max_length=30)),
                ('desciptions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('ds_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ds_name', models.CharField(max_length=30)),
                ('desciptions', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('emp_age', models.IntegerField()),
                ('emp_contact', models.CharField(max_length=13)),
                ('salary', models.IntegerField()),
                ('emp_address', models.TextField(max_length=100)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.designation')),
            ],
        ),
    ]
